version: "3"

services:
        mariadb:
             container_name: mariadb
             image: mariadb
             build : ./requirements/mariadb/ 
             restart : always 
             volumes:
               - db:/var/lib/mysql
             env_file:
                - .env
             networks:
                     - inception
             expose:
                - "3306"
        wordpress:
                container_name: wordpress
                image: wordpress
                build: ./requirements/wordpress/
                volumes:
                    - wordpress:/var/www/wordpress
                env_file:
                  - .env
                restart: always
                depends_on:
                    - mariadb
                networks:
                  - inception
                expose:
                    - "9000"
        nginx:
            container_name: nginx
            image: nginx
            build: ./requirements/nginx
            restart: always
            volumes:
                   - wordpress:/var/www/wordpress
            ports:
                    - 443:443
            networks:
                    - inception
            depends_on: 
                    - wordpress
        redis:
                      container_name: redis
                      image: redis
                      build:  ./requirements/bonus/redis-container
                      restart: always
                      networks:
                        - inception
                      expose:
                       - "6379"
                      ports:
                        - 6379:6739

        ftp:
                container_name: ftp
                image: ftp
                build: ./requirements/bonus/ftp-container
                restart: always
                volumes:
                  - wordpress:/home/ichouare/ftp/files
                env_file:
                    - .env
                networks:
                  - inception
                ports:
                   - "21:21"
        adminer:
            container_name: adminer
            image: adminer
            build: ./requirements/bonus/adminer-container
            restart: always
            networks:
                - inception
            ports:
              - 8080:8080
        cAdvisor:
            container_name: cadvisor
            image: cadvisor
            build: ./requirements/bonus/cadvisor
            networks:
                - inception
            restart: always
            ports:
                - 8081:8080
            volumes:
              - /:/rootfs:ro
              - /var/run:/var/run:rw
              - /sys:/sys:ro
              - /var/lib/docker/:/var/lib/docker:ro
volumes:
        wordpress:
           name: wordpress
           driver: local
           driver_opts:
              type: 'none'
              o: 'bind'
              device: '/home/ichouare/data/website/'
        db:
          name: db
          driver: local
          driver_opts:
            type: 'none'
            o: 'bind'
            device: '/home/ichouare/data/mariadb'
networks:
        inception:
