version: "3"

services:
        mariadb:
             container_name: mariadb
             build : ./requirements/mariadb/ 
             restart : always 
               #volumes:
               # - ./db:/var/lib/mysql
             networks:
                     - inception
        nginx:
            container_name: nginx
            build: ./requirements/nginx
            restart: always
            volumes:
                   - ./websites:/var/www/inception
            ports:
                    - 443:443
            networks:
                    - inception
            depends_on: 
                    - wordpress
        wordpress:
                container_name: wordpress
                build: ./requirements/wordpress/
                volumes:
                    - ./websites:/var/www/wordpress
                restart: always
                depends_on:
                    - mariadb      
                networks:
                  - inception
volumes:
        websites:
                driver: local
                driver_opts:
                        type: 'none'
                        o: 'mount'
                        device: '/home/ichouare/data/'
        db:
                driver: local
                driver_opts:
                        type: 'none'
                        o: 'mount'
                        device: '/home/ichouare/data/mariadb/'
networks:
        inception:

